from config import USE_MOCK_CLIENT, USE_OPENAI_CLIENT, USE_HUGGINGFACE_CLIENT

print("USE_MOCK_CLIENT:", USE_MOCK_CLIENT)
print("USE_OPENAI_CLIENT:", USE_OPENAI_CLIENT)
print("USE_HUGGINGFACE_CLIENT:", USE_HUGGINGFACE_CLIENT)
